"""add_motivo_to_sala_espera

Revision ID: 1f275ca4e1c9
Revises: 823f6749764a
Create Date: 2026-06-21 19:49:56.731149
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f275ca4e1c9'
down_revision: Union[str, None] = '823f6749764a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sala_espera', sa.Column('motivo', sa.String(length=500), server_default='-', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sala_espera', 'motivo')
    # ### end Alembic commands ###
