"""add_subtipo_to_resultados

Revision ID: 46fabc397fef
Revises: cd48075b2956
Create Date: 2026-06-25 16:16:35.319784
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46fabc397fef'
down_revision: Union[str, None] = 'cd48075b2956'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    subtipo_enum = sa.Enum('ECOGRAFY', 'RADIOLOGY', 'TOMOGRAPHY', 'RESONANCE', 'MAMMOGRAPHY', 'DENSITOMETRY', 'ECODOPPLER', 'ENDOSCOPY', name='subtipo_estudio_enum')
    subtipo_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('resultados_estudios', sa.Column('subtipo', subtipo_enum, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resultados_estudios', 'subtipo')
    subtipo_enum = sa.Enum('ECOGRAFY', 'RADIOLOGY', 'TOMOGRAPHY', 'RESONANCE', 'MAMMOGRAPHY', 'DENSITOMETRY', 'ECODOPPLER', 'ENDOSCOPY', name='subtipo_estudio_enum')
    subtipo_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
