"""initial

Revision ID: 84d45f6d7169
Revises: 
Create Date: 2026-05-15 16:25:39.162955
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '84d45f6d7169'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pacientes',
    sa.Column('id_paciente', sa.Integer(), nullable=False),
    sa.Column('datos_personales', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_paciente')
    )
    op.create_index(op.f('ix_pacientes_id_paciente'), 'pacientes', ['id_paciente'], unique=False)
    op.create_table('alertas_clinicas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_paciente', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('CONTRAINDICACION_ABSOLUTA', 'ALERGIA', 'RIESGO_SANGRADO', 'EMBARAZO', name='tipo_alerta_clinica'), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_paciente'], ['pacientes.id_paciente'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alertas_clinicas_id_paciente'), 'alertas_clinicas', ['id_paciente'], unique=False)
    op.create_table('alertas_farmacologicas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_paciente', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('ALERGIA_MEDICAMENTOSA', 'INSUFICIENCIA_RENAL', 'INSUFICIENCIA_HEPATICA', 'EMBARAZO', name='tipo_alerta_farmacologica'), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_paciente'], ['pacientes.id_paciente'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alertas_farmacologicas_id_paciente'), 'alertas_farmacologicas', ['id_paciente'], unique=False)
    op.create_table('coberturas_medicas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_paciente', sa.Integer(), nullable=False),
    sa.Column('id_obra_social', sa.Integer(), nullable=False),
    sa.Column('nombre_obra_social', sa.String(length=200), nullable=False),
    sa.Column('codigo_plan', sa.String(length=50), nullable=True),
    sa.Column('numero_afiliado', sa.String(length=50), nullable=True),
    sa.Column('vigente_desde', sa.Date(), nullable=True),
    sa.Column('vigente_hasta', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id_paciente'], ['pacientes.id_paciente'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coberturas_medicas_id_paciente'), 'coberturas_medicas', ['id_paciente'], unique=False)
    op.create_table('episodios',
    sa.Column('id_episodio', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_paciente', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('consulta-externa', 'internacion', 'guardia', 'cirugia', name='tipo_episodio'), nullable=False),
    sa.Column('estado', sa.Enum('open', 'closed', name='estado_episodio'), nullable=False),
    sa.Column('id_sede', sa.Integer(), nullable=False),
    sa.Column('id_medico_responsable', sa.Integer(), nullable=False),
    sa.Column('diagnostico_principal', sa.String(length=500), nullable=True),
    sa.Column('fecha_apertura', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_cierre', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_paciente'], ['pacientes.id_paciente'], ),
    sa.PrimaryKeyConstraint('id_episodio')
    )
    op.create_index(op.f('ix_episodios_id_paciente'), 'episodios', ['id_paciente'], unique=False)
    op.create_table('ordenes',
    sa.Column('id_orden', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_paciente', sa.Integer(), nullable=False),
    sa.Column('tipo_estudio', sa.Enum('Laboratorio', 'Imagen', 'Anatomia_Patologica', name='tipo_estudio'), nullable=False),
    sa.Column('descripcion_pedido', sa.String(length=500), nullable=True),
    sa.Column('prioridad', sa.Enum('Normal', 'Urgente', 'Emergencia', name='prioridad_orden'), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['id_paciente'], ['pacientes.id_paciente'], ),
    sa.PrimaryKeyConstraint('id_orden')
    )
    op.create_index(op.f('ix_ordenes_id_paciente'), 'ordenes', ['id_paciente'], unique=False)
    op.create_table('resultados_estudios',
    sa.Column('id_resultado', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_orden', sa.Integer(), nullable=True),
    sa.Column('id_paciente', sa.Integer(), nullable=False),
    sa.Column('tipo_estudio', sa.Enum('Laboratorio', 'Imagen', 'Anatomia_Patologica', name='tipo_estudio_resultado'), nullable=False),
    sa.Column('id_profesional_firmante', sa.String(length=200), nullable=False),
    sa.Column('fecha_resultado', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('informe_resumen', sa.Text(), nullable=True),
    sa.Column('id_externo_estudio', sa.String(length=100), nullable=True),
    sa.Column('titulo', sa.String(length=300), nullable=True),
    sa.Column('resumen', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_paciente'], ['pacientes.id_paciente'], ),
    sa.PrimaryKeyConstraint('id_resultado')
    )
    op.create_index(op.f('ix_resultados_estudios_id_paciente'), 'resultados_estudios', ['id_paciente'], unique=False)
    op.create_table('actos_medicos',
    sa.Column('id_acto_medico', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_episodio', sa.Integer(), nullable=False),
    sa.Column('codigo_nomenclador', sa.String(length=20), nullable=True),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('tipo', sa.Enum('consulta', 'estudio-laboratorio', 'estudio-imagen', 'procedimiento', 'cirugia', 'medicacion', 'descartable', name='tipo_acto_medico'), nullable=False),
    sa.Column('id_profesional', sa.Integer(), nullable=True),
    sa.Column('fecha_realizacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_episodio'], ['episodios.id_episodio'], ),
    sa.PrimaryKeyConstraint('id_acto_medico')
    )
    op.create_index(op.f('ix_actos_medicos_id_episodio'), 'actos_medicos', ['id_episodio'], unique=False)
    op.create_table('evoluciones',
    sa.Column('id_evolucion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_episodio', sa.Integer(), nullable=False),
    sa.Column('id_profesional', sa.Integer(), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_episodio'], ['episodios.id_episodio'], ),
    sa.PrimaryKeyConstraint('id_evolucion')
    )
    op.create_index(op.f('ix_evoluciones_id_episodio'), 'evoluciones', ['id_episodio'], unique=False)
    op.create_table('movimientos_internacion',
    sa.Column('id_movimiento', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_episodio', sa.Integer(), nullable=False),
    sa.Column('id_paciente', sa.Integer(), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=False),
    sa.Column('habitacion', sa.String(length=100), nullable=True),
    sa.Column('cama', sa.String(length=50), nullable=False),
    sa.Column('fecha_ingreso', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('medico_solicitante', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['id_episodio'], ['episodios.id_episodio'], ),
    sa.ForeignKeyConstraint(['id_paciente'], ['pacientes.id_paciente'], ),
    sa.PrimaryKeyConstraint('id_movimiento')
    )
    op.create_index(op.f('ix_movimientos_internacion_id_episodio'), 'movimientos_internacion', ['id_episodio'], unique=False)
    op.create_index(op.f('ix_movimientos_internacion_id_paciente'), 'movimientos_internacion', ['id_paciente'], unique=False)
    op.create_table('recetas',
    sa.Column('id_receta', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_paciente', sa.Integer(), nullable=False),
    sa.Column('id_evolucion', sa.Integer(), nullable=True),
    sa.Column('medicamento', sa.String(length=300), nullable=False),
    sa.Column('indicaciones', sa.Text(), nullable=True),
    sa.Column('estado', sa.Enum('Activa', 'Suspendida', 'Dispensada', name='estado_receta'), nullable=False),
    sa.ForeignKeyConstraint(['id_evolucion'], ['evoluciones.id_evolucion'], ),
    sa.ForeignKeyConstraint(['id_paciente'], ['pacientes.id_paciente'], ),
    sa.PrimaryKeyConstraint('id_receta')
    )
    op.create_index(op.f('ix_recetas_id_paciente'), 'recetas', ['id_paciente'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recetas_id_paciente'), table_name='recetas')
    op.drop_table('recetas')
    op.drop_index(op.f('ix_movimientos_internacion_id_paciente'), table_name='movimientos_internacion')
    op.drop_index(op.f('ix_movimientos_internacion_id_episodio'), table_name='movimientos_internacion')
    op.drop_table('movimientos_internacion')
    op.drop_index(op.f('ix_evoluciones_id_episodio'), table_name='evoluciones')
    op.drop_table('evoluciones')
    op.drop_index(op.f('ix_actos_medicos_id_episodio'), table_name='actos_medicos')
    op.drop_table('actos_medicos')
    op.drop_index(op.f('ix_resultados_estudios_id_paciente'), table_name='resultados_estudios')
    op.drop_table('resultados_estudios')
    op.drop_index(op.f('ix_ordenes_id_paciente'), table_name='ordenes')
    op.drop_table('ordenes')
    op.drop_index(op.f('ix_episodios_id_paciente'), table_name='episodios')
    op.drop_table('episodios')
    op.drop_index(op.f('ix_coberturas_medicas_id_paciente'), table_name='coberturas_medicas')
    op.drop_table('coberturas_medicas')
    op.drop_index(op.f('ix_alertas_farmacologicas_id_paciente'), table_name='alertas_farmacologicas')
    op.drop_table('alertas_farmacologicas')
    op.drop_index(op.f('ix_alertas_clinicas_id_paciente'), table_name='alertas_clinicas')
    op.drop_table('alertas_clinicas')
    op.drop_index(op.f('ix_pacientes_id_paciente'), table_name='pacientes')
    op.drop_table('pacientes')
    # ### end Alembic commands ###
