"""refactor_recetas_items

Revision ID: 9c776f8fac73
Revises: 546e3dda5dcd
Create Date: 2026-06-04 17:48:45.515308
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c776f8fac73'
down_revision: Union[str, None] = '546e3dda5dcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items_receta',
    sa.Column('id_item', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_receta', sa.Integer(), nullable=False),
    sa.Column('medicamento', sa.String(length=300), nullable=False),
    sa.Column('indicaciones', sa.Text(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_receta'], ['recetas.id_receta'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_item')
    )
    op.create_index(op.f('ix_items_receta_id_receta'), 'items_receta', ['id_receta'], unique=False)
    op.drop_column('recetas', 'medicamento')
    op.drop_column('recetas', 'indicaciones')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recetas', sa.Column('indicaciones', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('recetas', sa.Column('medicamento', sa.VARCHAR(length=300), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_items_receta_id_receta'), table_name='items_receta')
    op.drop_table('items_receta')
    # ### end Alembic commands ###
