"""add_receta_fecha_creacion_and_orden_origen

Revision ID: 441cec87cd4a
Revises: 7dae358b5431
Create Date: 2026-07-10 07:18:10.631624
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '441cec87cd4a'
down_revision: Union[str, None] = '7dae358b5431'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    origen_orden_enum = sa.Enum('Internacion', 'Ambulatorio', 'Turno', name='origen_orden')
    origen_orden_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('ordenes', sa.Column('origen', sa.Enum('Internacion', 'Ambulatorio', 'Turno', name='origen_orden'), nullable=True))
    op.add_column('recetas', sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recetas', 'fecha_creacion')
    op.drop_column('ordenes', 'origen')
    origen_orden_enum = sa.Enum('Internacion', 'Ambulatorio', 'Turno', name='origen_orden')
    origen_orden_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
