"""Replace alerta_clinica_alerta_farmacologica with alerta_clinica_paciente and antecedente_paciente

Revision ID: 546e3dda5dcd
Revises: 681de181a35e
Create Date: 2026-05-18 17:31:51.497072
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '546e3dda5dcd'
down_revision: Union[str, None] = '681de181a35e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerta_clinica_paciente',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_paciente', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('ALERGIA', 'DISPOSITIVO_IMPLANTADO', 'CONDICION_CRITICA', 'RIESGO_INFECCIOSO', 'CONTRAINDICACION', name='tipo_consideracion'), nullable=False),
    sa.Column('severidad', sa.Enum('LEVE', 'MODERADA', 'SEVERA', 'CRITICA', name='severidad_alerta'), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('estado', sa.Enum('ACTIVA', 'RESUELTA', name='estado_alerta'), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id_medico_registro', sa.Integer(), nullable=False),
    sa.Column('fecha_resolucion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id_medico_resolucion', sa.Integer(), nullable=True),
    sa.Column('motivo_resolucion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_paciente'], ['pacientes.id_paciente'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerta_clinica_paciente_id_paciente'), 'alerta_clinica_paciente', ['id_paciente'], unique=False)
    op.create_table('antecedente_paciente',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_paciente', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('QUIRURGICO', 'FAMILIAR', 'PATOLOGICO', 'HABITO', name='tipo_antecedente'), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('fecha_suceso', sa.Date(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id_medico_registro', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_paciente'], ['pacientes.id_paciente'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_antecedente_paciente_id_paciente'), 'antecedente_paciente', ['id_paciente'], unique=False)
    op.drop_index(op.f('ix_alertas_clinicas_id_paciente'), table_name='alertas_clinicas')
    op.drop_table('alertas_clinicas')
    op.drop_index(op.f('ix_alertas_farmacologicas_id_paciente'), table_name='alertas_farmacologicas')
    op.drop_table('alertas_farmacologicas')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alertas_farmacologicas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_paciente', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tipo', postgresql.ENUM('ALERGIA_MEDICAMENTOSA', 'INSUFICIENCIA_RENAL', 'INSUFICIENCIA_HEPATICA', 'EMBARAZO', name='tipo_alerta_farmacologica'), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_paciente'], ['pacientes.id_paciente'], name=op.f('alertas_farmacologicas_id_paciente_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('alertas_farmacologicas_pkey'))
    )
    op.create_index(op.f('ix_alertas_farmacologicas_id_paciente'), 'alertas_farmacologicas', ['id_paciente'], unique=False)
    op.create_table('alertas_clinicas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_paciente', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tipo', postgresql.ENUM('CONTRAINDICACION_ABSOLUTA', 'ALERGIA', 'RIESGO_SANGRADO', 'EMBARAZO', name='tipo_alerta_clinica'), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_paciente'], ['pacientes.id_paciente'], name=op.f('alertas_clinicas_id_paciente_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('alertas_clinicas_pkey'))
    )
    op.create_index(op.f('ix_alertas_clinicas_id_paciente'), 'alertas_clinicas', ['id_paciente'], unique=False)
    op.drop_index(op.f('ix_antecedente_paciente_id_paciente'), table_name='antecedente_paciente')
    op.drop_table('antecedente_paciente')
    op.drop_index(op.f('ix_alerta_clinica_paciente_id_paciente'), table_name='alerta_clinica_paciente')
    op.drop_table('alerta_clinica_paciente')
    # ### end Alembic commands ###
