"""make_id_episodio_nullable

Revision ID: 823f6749764a
Revises: fbb4865fb2e0
Create Date: 2026-06-21 18:55:33.245995
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '823f6749764a'
down_revision: Union[str, None] = 'fbb4865fb2e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sala_espera', 'id_episodio',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sala_espera', 'id_episodio',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
