"""create_solicitudes_cama_table

Revision ID: d77dfb3fa6ee
Revises: 46fabc397fef
Create Date: 2026-06-25 16:58:19.585252
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd77dfb3fa6ee'
down_revision: Union[str, None] = '46fabc397fef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitudes_cama',
    sa.Column('id_solicitud', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_paciente', sa.Integer(), nullable=False),
    sa.Column('id_episodio', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('prioridad', sa.String(length=20), nullable=False),
    sa.Column('sector', sa.String(length=120), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('cama', sa.String(length=50), nullable=True),
    sa.Column('habitacion', sa.String(length=100), nullable=True),
    sa.Column('motivo_rechazo', sa.Text(), nullable=True),
    sa.Column('fecha_solicitud', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_resolucion', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_episodio'], ['episodios.id_episodio'], ),
    sa.ForeignKeyConstraint(['id_paciente'], ['pacientes.id_paciente'], ),
    sa.PrimaryKeyConstraint('id_solicitud')
    )
    op.create_index(op.f('ix_solicitudes_cama_estado'), 'solicitudes_cama', ['estado'], unique=False)
    op.create_index(op.f('ix_solicitudes_cama_id_episodio'), 'solicitudes_cama', ['id_episodio'], unique=False)
    op.create_index(op.f('ix_solicitudes_cama_id_paciente'), 'solicitudes_cama', ['id_paciente'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_solicitudes_cama_id_paciente'), table_name='solicitudes_cama')
    op.drop_index(op.f('ix_solicitudes_cama_id_episodio'), table_name='solicitudes_cama')
    op.drop_index(op.f('ix_solicitudes_cama_estado'), table_name='solicitudes_cama')
    op.drop_table('solicitudes_cama')
    # ### end Alembic commands ###
