"""add_sala_espera

Revision ID: fbb4865fb2e0
Revises: 9c776f8fac73
Create Date: 2026-06-19 20:45:06.218848
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbb4865fb2e0'
down_revision: Union[str, None] = '9c776f8fac73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sala_espera',
    sa.Column('id_espera', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_paciente', sa.Integer(), nullable=False),
    sa.Column('id_episodio', sa.Integer(), nullable=False),
    sa.Column('id_medico', sa.Integer(), nullable=False),
    sa.Column('id_sede', sa.Integer(), nullable=False),
    sa.Column('id_turno_m2', sa.Integer(), nullable=True),
    sa.Column('fecha_llegada', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_turno', sa.DateTime(timezone=True), nullable=True),
    sa.Column('prioridad', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('Esperando', 'Llamado', 'Atendido', 'Ausente', name='estado_sala_espera'), nullable=False),
    sa.Column('consultorio', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_episodio'], ['episodios.id_episodio'], ),
    sa.ForeignKeyConstraint(['id_paciente'], ['pacientes.id_paciente'], ),
    sa.PrimaryKeyConstraint('id_espera')
    )
    op.create_index(op.f('ix_sala_espera_id_episodio'), 'sala_espera', ['id_episodio'], unique=False)
    op.create_index(op.f('ix_sala_espera_id_medico'), 'sala_espera', ['id_medico'], unique=False)
    op.create_index(op.f('ix_sala_espera_id_paciente'), 'sala_espera', ['id_paciente'], unique=False)
    op.create_index(op.f('ix_sala_espera_id_sede'), 'sala_espera', ['id_sede'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sala_espera_id_sede'), table_name='sala_espera')
    op.drop_index(op.f('ix_sala_espera_id_paciente'), table_name='sala_espera')
    op.drop_index(op.f('ix_sala_espera_id_medico'), table_name='sala_espera')
    op.drop_index(op.f('ix_sala_espera_id_episodio'), table_name='sala_espera')
    op.drop_table('sala_espera')
    # ### end Alembic commands ###
