from enum import Enum


class TipoAlertaFarmacologica(str, Enum):
    ALERGIA_MEDICAMENTOSA = "ALERGIA_MEDICAMENTOSA"
    INSUFICIENCIA_RENAL = "INSUFICIENCIA_RENAL"
    INSUFICIENCIA_HEPATICA = "INSUFICIENCIA_HEPATICA"
    EMBARAZO = "EMBARAZO"
